import React from "react";
import { ShieldCheck } from "lucide-react";

const TermsPage = () => {
  return (
    <div className="p-6 sm:p-10 max-w-4xl mx-auto text-gray-800 sm:mt-[10vh]">
      <div className="flex items-center justify-center mb-10">
        <ShieldCheck className="w-10 h-10 text-green-600 mr-3" />
        <h1 className="text-5xl font-extrabold text-green-700 text-center">
          Terms & Conditions
        </h1>
      </div>

      <div className="space-y-10 text-base sm:text-xl leading-relaxed">
        <Section title="Terms of Use & Privacy Policy">
          <p className="whitespace-pre-line">
            {`This document is an electronic record in accordance with the Information Technology Act, 2000 and its applicable rules, and the amended provisions related to electronic records in various statutes. This record is generated by a computer system and does not require any physical or digital signatures.

This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which mandates publishing rules and regulations, privacy policy, and Terms of Use for access to or usage of the domain https://www.peros.in ("Website"), including its related mobile site and application (hereinafter referred to as the "Platform").

The Platform is owned by PEROS, a company incorporated under the Companies Act, 1956, with its registered office at:
GR FLOOR, CHAWL NO 21, RAM NAGAR CHAWL, KALYAN ULHASNAGAR ROAD,
BEHIND SHREE RAM TALKIES, Ulhasnagar POWAI CHOWK, Ulhasnagar, India.
(hereinafter referred to as "Platform Owner", "we", "us", "our").

By using the Platform and its services, you agree to the following Terms and Conditions ("Terms of Use"). These Terms, including applicable policies, govern your relationship with the Platform Owner. If you transact on the Platform, these terms and policies will apply. Merely using the Platform establishes a binding agreement with the Platform Owner.

Any additional or conflicting terms proposed by you are expressly rejected.

These Terms may be modified at any time without prior notice. It is your responsibility to review them periodically.

"User", "you", or "your" refers to any natural or legal person who agrees to access the Platform or use our services.

ACCESSING, BROWSING, OR USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THESE TERMS. PLEASE READ CAREFULLY.

The Services require you to provide accurate, complete information during registration. You are responsible for all activities under your account.

We do not guarantee the accuracy or completeness of the content on the Platform. Your use of any information or material is entirely at your own risk, for which we are not liable.

All content on the Platform, including design, layout, and graphics, is proprietary. Unauthorized use may result in legal action.

You agree to:
- Pay applicable service charges.
- Use the Platform only for lawful purposes.
- Accept that external links will be governed by their own terms and privacy policies.

By initiating a transaction, you enter into a legally binding agreement with the Platform Owner.

You shall indemnify and hold harmless the Platform Owner and affiliates from any claims or liabilities arising out of your breach of these Terms or applicable laws.

Neither party shall be liable for failure to perform obligations due to force majeure events.

These Terms are governed by Indian law. All disputes will be subject to the exclusive jurisdiction of courts in Ulhasnagar, Maharashtra.

All communications related to these Terms must be addressed through the contact details provided on the website.

---

**Privacy Policy**

This Privacy Policy explains how PEROS and its affiliates ("we", "our", "us") collect, use, share, and safeguard your personal information on https://www.peros.in (the "Platform").

By using the Platform, you agree to this Privacy Policy and the applicable Terms of Use.

We collect your personal data such as:
- Name, DOB, address, phone, email, payment details, biometric data (if used).
- Data you provide during registration and use of the Platform.
- Transactional data and behavioral tracking for analysis.

We do **not** offer services outside India. Your data is processed and stored in India.

We may use your personal data to:
- Fulfill orders, enhance services, resolve disputes, send updates and offers.
- Prevent fraud, conduct research, enforce terms, and more.

You may opt-out of marketing communications.

We share your data with:
- Group companies, sellers, partners, logistics, payment providers, and third parties.
- Law enforcement if required by law or necessary to protect rights and safety.

We take reasonable security precautions but cannot guarantee full security of data transmitted online. You are responsible for safeguarding your account credentials.

---

**Data Retention & Deletion**

You may delete your account via profile settings or by contacting us. Deletion will be delayed if services or disputes are pending.

We retain data as long as needed for legitimate or legal reasons, even post-deletion, in anonymized form.

---

**Your Rights & Consent**

You can access and update your data through the Platform.

By using the Platform, you consent to the collection, processing, and use of your data as outlined. If you share data of others, you confirm that you have the authority to do so.

You may withdraw consent by writing to the Grievance Officer. Withdrawal may limit your access to services.

---

**Policy Updates**

Changes to this Privacy Policy- Please check our Privacy Policy periodically for changes. We may update this Privacy Policy to reflect changes to our information practices. We may alert / notify you about the significant changes to the Privacy Policy, in the manner as may be required under applicable laws.

---
`}
          </p>
        </Section>

        <Section title="Refund Policy">
          <p>We do not offer any kind of refunds or returns under any circumstances.</p>
        </Section>

        <Section title="Shipping Policy">
          <p>Products purchased through the Platform will be delivered within 7 business days.</p>
        </Section>
      </div>

      <p className="text-sm text-gray-500 text-center mt-16">
        Last updated: <span className="font-medium">May 12, 2025</span>
        <br />
        &copy; 2025 Peros. All rights reserved.
      </p>
    </div>
  );
};

const Section = ({ title, children }) => (
  <section className="bg-gray-50 hover:bg-gray-100 transition-all duration-200 border border-gray-300 rounded-xl p-6 shadow-md">
    <h2 className="text-2xl font-bold mb-3 text-green-700">{title}</h2>
    <div className="text-gray-700">{children}</div>
  </section>
);

export default TermsPage;
